#!/bin/bash
#BSUB -J train_2023_03_drawness
#BSUB -q gpuv100
#BSUB -n 4
#BSUB -gpu "num=1:mode=exclusive_process"
#BSUB -R "rusage[mem=32GB] span[hosts=1]"
#BSUB -W 12:00
#BSUB -o /zhome/81/b/206091/logs/train_2023_03_drawness_%J.out
#BSUB -e /zhome/81/b/206091/logs/train_2023_03_drawness_%J.err

source /zhome/81/b/206091/petra-env/bin/activate
module load gcc/13.4.0-binutils-2.44
module load cuda/12.1

# Regular training on Lichess 2023-03 (SF depth-18) with drawness-capable anchor.
#
# Init: lichess_2023_03_endgame/best.pt (rank 21.6, first KR vs KR pass)
#
# Primary dataset: dataset_2023_03_sf18.pt — 800k positions, SF depth-18 labels,
#   full board (max_pieces=32), min_decisive=0.0. Maintains geometry rank through
#   diverse position distribution.
#
# Anchor: endgame_drawness.pt — generated by gen_endgame_drawness.sh.
#   Stages 1/2/4/5 (decisive, drawness=0.0) + 9/10/11 (structural draws, drawness=1.0).
#   Explicit drawness_mask/drawness_targets so --draw-reg trains from clean signal,
#   not from the |v|<0.15 heuristic used by the old endgame_sf15.pt anchor.
#   ~120k positions. Run gen_endgame_drawness.sh before submitting this job.
#
# draw-reg 0.05: higher than the 0.02 used for lichess_2023_03_endgame because
#   explicit labels make the BCE signal trustworthy — no risk of mislabelling
#   balanced Lichess positions as structural draws.
#
# Gates (probe_geometry after training):
#   rank        >= 21.6  (no regression from init)
#   win·draw cos blunt — use as collapse detector (>0.5 = panic) not as target
#   KR vs KR |value| < 0.35
#   drawness: KR vs KR > 0.7, sharp balanced < 0.3

BLACKHOLE="/dtu/blackhole/0b/206091"
HOME_DIR="/zhome/81/b/206091"

python3 -u ${HOME_DIR}/Petra-ver2/src/train.py \
    --dataset        ${BLACKHOLE}/dataset_2023_03_sf18.pt \
    --anchor-dataset ${HOME_DIR}/Petra-ver2/data/endgame_drawness.pt \
    --anchor-frac    0.15 \
    --init-model     ${HOME_DIR}/Petra-ver2/models/lichess_2023_03_endgame/best.pt \
    --rank-reg       0.1 \
    --draw-reg       0.05 \
    --num-workers    0 \
    --weight-decay   5e-4 \
    --lr             3e-4 \
    --epochs         20 \
    --geo-patience   3 \
    --out            ${HOME_DIR}/Petra-ver2/models/lichess_2023_03_drawness
